#!/usr/bin/env python3
# ########################################################################### #
#   shebang: 1                                                                #
#                                                          :::      ::::::::  #
#   visual_generator.py                                  :+:      :+:    :+:  #
#                                                      +:+ +:+         +:+    #
#   By: jay-k <jay-k@student.42.fr>                  +#+  +:+       +#+       #
#                                                  +#+#+#+#+#+   +#+          #
#   Created: 2026/08/25 11:19:20 by jkrishna            #+#    #+#            #
#   Updated: 2026/08/27 22:20:22 by jay-k              ###   ########.fr      #
#                                                                             #
# ########################################################################### #


from pathlib import Path
from parser.map_parser import Parser
from typing import Any
from textual.app import App, ComposeResult
from textual.containers import Container, Horizontal, VerticalScroll
from textual.widgets import DataTable, Footer, Header, Static
from textual.widgets import Select
from textual.screen import ModalScreen

from core.engine import Engine
from visuals.airspace_map import AirspaceMap

# ┌──────────────────────────────────────────────────────────────┐
# │ HEADER                                                       │
# ├──────────────────────────────────┬───────────────────────────┤
# │                                  │ EVENT LOGS                │
# │                                  |                           |
# │           AIRSPACE MAP           |                           │
# │                                  │                           │
# │                                  │                           │
# ├──────────────────────────────────┴───────────────────────────┤
# │ DRONES                           │ SUMMARY                   │
# ├──────────────────────────────────┴───────────────────────────┤
# │ FOOTER / CONTROLS                                            │
# └──────────────────────────────────────────────────────────────┘


#  EVENT LOG  #

class EventLog(VerticalScroll):
    """Display the events generated by the simulation."""

    TITLE = "EVENT LOG"

    # the styling language used in Textual
    # CSS (Cascading Style Sheets) adapted for terminal UIs.
    DEFAULT_CSS = """
    EventLog {
        width: 100;
        height: 100;
        padding: 1;
        overflow-y: auto;
    }
    """

    def __init__(
        self,
        engine: Engine,
        **kwargs: Any,
    ) -> None:
        """Initialize the event log.

        Args:
            engine: The simulation engine containing the event history.
            **kwargs: Additional arguments passed to the Textual widget.
        """
        super().__init__(**kwargs)

        self.engine = engine

    def update_log(self) -> None:
        """Refresh the event log using the engine's current events.

        The existing widgets are removed and replaced by a single widget
        containing all recorded simulation events.
        """
        events = self.engine.event_log

        self.remove_children()

        if not events:
            self.mount(Static("No events yet."))
            return

        self.mount(
            Static(
                "\n".join(str(event) for event in events)
            )
        )


#   SUMMARY   #

class Summary(Static):
    """Display statistics describing the current simulation state."""

    TITLE = "SUMMARY"

    DEFAULT_CSS = """
    Summary {
        width: 100%;
        height: 100%;
        padding: 1;
        overflow: hidden;
    }
    """

    def __init__(
        self,
        engine: Engine,
        **kwargs: Any,
    ) -> None:
        """Initialize the simulation summary.

        Args:
            engine: The simulation engine providing the statistics.
            **kwargs: Additional arguments passed to the Textual widget.
        """
        super().__init__(**kwargs)

        self.engine = engine

    def update_summary(self) -> None:
        """Refresh the displayed simulation statistics.

        The summary shows the total number of drones, drones currently in
        connections, drones in transit, completed drones, total path cost,
        and the number of simulation ticks.
        """
        total_drones = self.engine.graph.total_drones

        drones_in_connections = sum(
            len(drones)
            for drones in self.engine.connection_stat.values()
        )

        drones_in_transit = 0

        for zone in self.engine.zone_stat:
            if zone not in (
                self.engine.graph.start_hub,
                self.engine.graph.end_hub,
            ):
                drones_in_transit += len(
                    self.engine.zone_stat[zone]
                )

        completed_drones = (
            self.engine.zone_occupancy.get(self.engine.graph.end_hub, 0)
        )

        tpc = int(self.engine.total_path_cost - self.engine.graph.total_drones)
        self.update(
            f"Total Drones: {total_drones}\n"
            f"Drones in Connection: {drones_in_connections}\n"
            f"Drones in Transit: {drones_in_transit}\n"
            f"Completed Drones: {completed_drones}\n"
            f"Total path cost: {tpc}\n"
            f"Total turns: {self.engine.ticks}\n"
        )


#  DRONE TABLE  #

class DroneTable(DataTable[str]):
    """Display the current state and route of every drone."""

    TITLE = "DRONE TABLE"

    DEFAULT_CSS = """
    Dronetable {
        width: 100%;
        height: 100%;
    }
    """

    def __init__(
        self,
        engine: Engine,
        **kwargs: Any,
    ) -> None:
        """Initialize the drone table.

        Args:
            engine: The simulation engine containing the drone states.
            **kwargs: Additional arguments passed to the Textual widget.
        """
        super().__init__(**kwargs)

        self.engine = engine

    def on_mount(self) -> None:
        """Create the columns when the table is mounted.

        The columns show the drone ID, current zone, remaining path,
        current status, and whether the drone is waiting.
        """

        self.add_columns(
            "DRONE_ID",
            "CURRENT ZONE",
            "PATH (NEXT -> ...)",
            "STATUS",
            "WAITING",
        )

    def update_table(self) -> None:
        """Refresh the table with the current state of all drones.

        The existing rows are removed and rebuilt from the engine's
        ``drones_stat`` data.
        """

        self.clear()

        for drone in self.engine.drones_stat:
            path = self.engine.drones_stat[drone]

            # Convert the list before slicing since
            # drones_stat stores path as deque
            path_list = list(path)

            if len(path_list) > 1:

                drone_path = " -> ".join(
                    zone.name
                    for zone in path_list[1:]
                )
            else:
                drone_path = ""

            # STATUS
            if drone.current_zone == self.engine.graph.end_hub:
                status = "IN_END_ZONE"
            else:
                status = "IN_TRANSIT"

            # WAITING
            if drone.current_zone == self.engine.graph.end_hub:
                waiting = "--"
            else:
                if drone in self.engine.waiting:
                    waiting = "YES"
                else:
                    waiting = "NO"

            self.add_row(
                str(drone.id),
                str(drone.current_zone.name),
                drone_path,
                status,
                waiting,
            )


#  MAP SELECTOR  #

class MapSelector(ModalScreen[str | None]):
    """Display a modal window allowing the user to select a map."""

    DEFAULT_CSS = """

    MapSelector {
        align: center middle;
    }

    #map-dialog {
        width: 70;
        height: auto;
        max-height: 80%;
        padding: 2;
        border: round cyan;
        background: $surface;
    }

    #map-title {
        width: 100%;
        content-align: center middle;
        margin-bottom: 1;
        text-style: bold;
    }

    #map-select {
        width: 100%
    }
    """

    def __init__(
        self,
        options: list[tuple[str, str]],
    ) -> None:
        """Initialize the map selection screen.

        Args:
            options: Map names and values displayed in the selection widget.
        """
        super().__init__()

        self.options = options

    def compose(self) -> ComposeResult:
        """Build the map selection interface.

        Returns:
            ComposeResult: The Textual widgets that form the modal screen.
        """
        with Container(id="map-dialog"):
            yield Static("Select Map", id="map-title")

            yield Select(
                self.options,
                prompt="Choose a map...",
                id="map-select",
            )

    def on_select_changed(
        self,
        event: Select.Changed,
    ) -> None:
        """Handle a map selection made by the user.

        Args:
            event: The Textual selection-change event containing the
                selected map value.
        """
        # Return the selected map

        if event.value is Select.BLANK:
            return

        # close modal and send selected value back to dashboard
        self.dismiss(str(event.value))

    # def on_key(self, event) -> None:
    #     # Allow escape to cancel

    #     if event.key == "escape":
    #         self.dismiss(None)


#   DASHBOARD   #

class Dashboard(App[None]):
    """Main Textual application for the Fly-in drone simulation.

    The dashboard combines the airspace map, event log, drone table,
    simulation summary, and keyboard controls into one interface.
    """

    TITLE = "FlyIn - Drone Traffic Simulation"

    BINDINGS = [
        ("q", "quit", "Quit"),
        ("Q", "quit", "Quit"),
        ("p", "toggle_pause", "Pause / Resume"),
        ("P", "toggle_pause", "Pause / Resume"),
        ("s", "step", "Step"),
        ("S", "step", "Step"),
        ("m", "change_map", "Change Map"),
        ("M", "change_map", "Change Map"),
        ("r", "restart", "Restart"),
        ("R", "restart", "Restart"),
    ]

    CSS = """
    Screen {
        layout: vertical
    }

    /* AREA BETWEEN HEADER & FOOTER*/
    #main {
        width: 100%;
        height: 1fr;
        layout: vertical;
    }

    /* AIRSPACE MAP & EVENT LOG*/
    #top {
        width: 100%;
        height: 2fr;
        layout: horizontal;
    }

    /* AIRSPACE MAP */
    #map {
        width: 3fr;
        height: 100%;
    }

    /* EVENT LOG */
    #events {
        width: 1fr;
        height: 100%;
        border: round yellow;
        padding: 1;
        overflow-y: auto;
    }

    /* BOTTOM SECTION */
    #bottom {
        width: 100%;
        height: 1fr;
        layout: horizontal;
    }

    /* DRONE TABLE */
    #drones {
        width: 6fr;
        height: 100%;
        border: round green;
    }

    /* SUMMARY */
    #summary {
        width: 1fr;
        height: 100%;
        border: round magenta;
        padding: 1;
        overflow: hidden;
    }
    """

    def __init__(
        self,
        engine: Engine,
        map_path: str
    ) -> None:
        """Initialize the simulation dashboard.

        Args:
            engine: Simulation engine controlling the drones and map.
            map_path: Path of the map currently being displayed.
        """
        super().__init__()

        self.paused = False
        self.engine = engine
        self.map_path = map_path
        self.sub_title = map_path

    # LAYOUT
    def compose(self) -> ComposeResult:
        """Build the complete dashboard layout.

        Returns:
            ComposeResult: The Textual widgets forming the dashboard.
        """

        yield Header()

        with Container(id="main"):

            # TOP
            with Horizontal(id="top"):

                yield AirspaceMap(self.engine, id="map")

                yield EventLog(self.engine, id="events")

            # BOTTOM
            with Horizontal(id="bottom"):

                yield DroneTable(self.engine, id="drones")

                yield Summary(self.engine, id="summary")

        yield Footer()

    # MOUNT
    def on_mount(self) -> None:
        """Initialize the dashboard and start the simulation timer.

        The dashboard is updated immediately after mounting and then
        simulation steps are executed automatically every second.
        """
        # Otherwise widget might be blank/stale
        self.update_dashboard()

        # Run one simulation step every second.
        self.set_interval(1.0, self.run_simulation)

    # SIMULATION
    def run_simulation(self) -> None:
        """Execute one simulation step and refresh the dashboard.

        A step is skipped when the simulation is paused or has already
        finished.
        """
        # if paused noting should happen
        if self.paused:
            return
        # if all derones at end_hub, dont continue
        if self.engine.is_finished():
            return

        self.engine.simulation()
        self.update_dashboard()

    # Below are actions: when u do the action,
    # what happens.

    # PAUSE ACTION
    def action_toggle_pause(self) -> None:
        """Toggle the simulation between paused and running states."""
        self.paused = not self.paused

    # STEP ACTION
    def action_step(self) -> None:
        """Execute exactly one simulation step.

        The step is ignored if the simulation has already finished.
        """
        if self.engine.is_finished():
            return

        self.engine.simulation()
        self.update_dashboard()

    # MAP SELECTION OPTION
    def action_change_map(self) -> None:
        """Open the map selection dialog.

        All ``.txt`` files under the ``maps`` directory are discovered and
        presented as selectable maps.
        """

        # collect all maps
        try:
            maps = sorted(Path("maps").rglob("*.txt"))
        except Exception:
            raise ValueError("Map files in .txt formats are missing")

        # Label and value
        options = [
            (str(path), str(path))
            for path in maps
        ]

        self.push_screen(MapSelector(options), self.map_selected)

    # RESET
    def action_restart(self) -> None:
        """Reset the current simulation to its initial state."""
        self.engine.reset()

    def map_selected(self, map_path: str | None) -> None:
        """Load a selected map and replace the current simulation engine.

        Args:
            map_path: Path of the selected map, or ``None`` if no map
                was selected.
        """

        if map_path is None:
            return

        parsed = Parser(map_path)
        graph_object = parsed.parser()

        self.engine = Engine(graph_object)
        self.map_path = map_path
        self.sub_title = map_path

        # Find the widget whose ID is map 
        # and make sure it is an AirspaceMap. Slly for others

        # AIRSPACE MAP
        airspace_map = self.query_one("#map", AirspaceMap)

        # EVENT LOG
        event_log = self.query_one("#events", EventLog)

        # DRONE TABLE
        drone_table = self.query_one("#drones", DroneTable)

        # SUMMARY
        summary = self.query_one("#summary", Summary)

        # Reuse existing widget but point them to new engine
        airspace_map.engine = self.engine
        event_log.engine = self.engine
        drone_table.engine = self.engine
        summary.engine = self.engine

        # after changing maps, simulation starts again
        self.paused = False

        # show new map/state
        self.update_dashboard()

    # UPDATE DASHBOARD
    def update_dashboard(self) -> None:
        """Refresh every visual component of the dashboard.

        The event log, drone table, summary, and airspace map are updated
        using the current state of the simulation engine.
        """

        # EVENT LOG
        event_log = self.query_one("#events", EventLog)
        event_log.update_log()

        # DRONE TABLE
        drone_table = self.query_one("#drones", DroneTable)
        drone_table.update_table()

        # SUMMARY
        summary = self.query_one("#summary", Summary)
        summary.update_summary()

        # AIRSPACE MAP
        airspace_map = self.query_one("#map", AirspaceMap)
        airspace_map.refresh_map()
